
package com.iti.structure;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "CDR_Struct", isSet = false )
    public class CDR_Struct implements IASN1PreparedElement {
            
    @ASN1String( name = "", 
        stringType =  UniversalTag.IA5String , isUCS = false )
    
        @ASN1Element ( name = "fieldName", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private String fieldName = null;
                
  
    @ASN1String( name = "", 
        stringType =  UniversalTag.IA5String , isUCS = false )
    
        @ASN1Element ( name = "fieldValue", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private String fieldValue = null;
                
  
        
        public String getFieldName () {
            return this.fieldName;
        }

        

        public void setFieldName (String value) {
            this.fieldName = value;
        }
        
  
        
        public String getFieldValue () {
            return this.fieldValue;
        }

        

        public void setFieldValue (String value) {
            this.fieldValue = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(CDR_Struct.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            